<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__email0</name>
   <tag></tag>
   <elementGuidId>37069fb8-6ac5-49a3-87e5-d96a3efc2978</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email0&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1be5b64b-c048-4a94-897e-f534421a99be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>input.ngModel</value>
      <webElementGuid>036c18b6-9ea8-4114-9167-dc803ae7c07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>th-input ng-pristine ng-valid ng-empty ng-valid-email ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-required ng-touched</value>
      <webElementGuid>4aeaed84-af7e-4fdf-8d24-b95f2b801a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>[
      {'with-icon': input.icon},
      {'with-prefix': input.prefix},
      {'with-postfix': input.postfix},
      {'disabled': input.ngDisabled}
    ]</value>
      <webElementGuid>d15c6422-9d2b-4ec6-b460-6e231410e5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>4143d5e6-8f58-44d9-ac99-d3f45feae15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email0</value>
      <webElementGuid>93235a1b-4528-406a-ab98-db111cd6c868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>input.ngRequired</value>
      <webElementGuid>f749ec7b-8ae9-42ad-9438-3f0aaade4985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>input.ngDisabled</value>
      <webElementGuid>7a804a11-c9c4-4bc9-8e39-7d8304c0f560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>input.ngBlur()</value>
      <webElementGuid>0dd23271-42cd-417c-b147-9b21f083690f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keypress</name>
      <type>Main</type>
      <value>input.ngKeypress</value>
      <webElementGuid>4c05ccca-2173-4f44-a3e7-4ef7d645475c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-min</name>
      <type>Main</type>
      <value>{{input.min}}</value>
      <webElementGuid>ef6b25d5-1bc9-408f-a645-22e0b09b07e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-max</name>
      <type>Main</type>
      <value>{{input.max}}</value>
      <webElementGuid>42e96585-f679-4e19-86aa-b3ddf301fe4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-step</name>
      <type>Main</type>
      <value>{{input.step}}</value>
      <webElementGuid>462238c5-185c-4d98-8f47-2950988f55c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>input.thOnChange()</value>
      <webElementGuid>2a6648fd-1620-4a76-8d75-a86770b06219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>input.ngReadonly</value>
      <webElementGuid>5355c880-ded9-4c03-8d37-8e48ca16ca88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Email address</value>
      <webElementGuid>f609c5f0-141f-48c7-9f9c-84d8d32da5ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>702e03ae-8088-4a0f-a390-2a3d043ff310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apollo-app&quot;)/div[@class=&quot;layout-default&quot;]/div[@class=&quot;th-modal-backdrop fullpage visible&quot;]/div[@class=&quot;th-modal-container fullpage fullpage-active&quot;]/div[@class=&quot;modal-flex-centering&quot;]/div[@class=&quot;th-modal contactsNewApollo fullpage apollo&quot;]/div[@class=&quot;modal-content&quot;]/contact-modal[1]/th-modal-body[1]/ng-transclude[1]/form[@class=&quot;max-width-1000 ml-auto mr-auto ng-pristine ng-invalid ng-invalid-required ng-valid-max-file-size ng-valid-invalid-file-format ng-valid-email ng-valid-pattern ng-valid-minlength ng-valid-maxlength&quot;]/th-card[1]/section[@class=&quot;th-card content-padding&quot;]/div[@class=&quot;card-content-container&quot;]/div[1]/th-card-content[1]/cc-email-fields[1]/ng-transclude[@class=&quot;th-radio-group ng-not-empty ng-valid&quot;]/div[1]/span[@class=&quot;th-row&quot;]/th-row[@class=&quot;row justify-content-start&quot;]/th-column[@class=&quot;col col-md-4&quot;]/label[@class=&quot;th-label&quot;]/span[@class=&quot;th-input-wrapper ng-empty ng-valid&quot;]/input[@class=&quot;th-input ng-pristine ng-valid ng-empty ng-valid-email ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-required ng-touched&quot;]</value>
      <webElementGuid>9348ff3c-e6bf-4a71-91ce-027bcb0fea67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email0']</value>
      <webElementGuid>bdeaf723-a16a-4e3c-9ea5-b2e9a82b6ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apollo-app']/div/div/div/div/div/div/contact-modal/th-modal-body/ng-transclude/form/th-card/section/div[2]/div/th-card-content/cc-email-fields/ng-transclude/div/span/th-row/th-column/label/span[2]/input</value>
      <webElementGuid>1056a8dc-e061-48fe-918b-335b8beb2bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-transclude/div/span/th-row/th-column/label/span[2]/input</value>
      <webElementGuid>38c09ae7-c880-469d-8e3e-249b17dad611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email0']</value>
      <webElementGuid>8d3bb5cc-e363-4142-8359-183625da2dbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
