<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__webSiteAddress</name>
   <tag></tag>
   <elementGuidId>b6f3245e-c509-431a-a82a-c7deda7269f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;webSiteAddress&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='webSiteAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f993737b-2f12-4725-9a08-9a99bf701740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>input.ngModel</value>
      <webElementGuid>62ea2a8f-7ea4-4f21-8e28-84e17ae22adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>th-input ng-pristine ng-untouched ng-valid ng-empty ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-required</value>
      <webElementGuid>a9cf1d90-4b3c-4074-a588-4df955964d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>[
      {'with-icon': input.icon},
      {'with-prefix': input.prefix},
      {'with-postfix': input.postfix},
      {'disabled': input.ngDisabled}
    ]</value>
      <webElementGuid>b0221dde-2d2a-4fcf-982e-5d3e32b4e390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3030df62-76f9-414a-999c-913a94feea6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>webSiteAddress</value>
      <webElementGuid>7e2f2496-7b47-4384-8d43-1f6cd3f2715b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>input.ngRequired</value>
      <webElementGuid>e05522b9-1a95-4396-83aa-97ac9dd5085c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>input.ngDisabled</value>
      <webElementGuid>1836bfbe-3f36-4a8f-bc07-78f158d2bd30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>input.ngBlur()</value>
      <webElementGuid>37658fb5-161b-440a-8846-140ca3f96245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keypress</name>
      <type>Main</type>
      <value>input.ngKeypress</value>
      <webElementGuid>3e357af5-4d92-4811-803b-75805d4e38e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-min</name>
      <type>Main</type>
      <value>{{input.min}}</value>
      <webElementGuid>485d9901-deff-4351-9d19-22fa54dd4966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-max</name>
      <type>Main</type>
      <value>{{input.max}}</value>
      <webElementGuid>f459a7f2-0365-48eb-9f38-b7ccde877cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-step</name>
      <type>Main</type>
      <value>{{input.step}}</value>
      <webElementGuid>b4db50d6-ad66-437f-8bcb-7df3b8db5025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>input.thOnChange()</value>
      <webElementGuid>0a9048d8-4557-429e-b23f-3429920a0f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>input.ngReadonly</value>
      <webElementGuid>2280e68c-4ef1-4976-a1e9-bb4f6af0c7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Web address</value>
      <webElementGuid>2c05c1cf-4d1f-42eb-9e62-746752e612c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4230a06f-4e0f-4212-ab62-14d63691b72c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apollo-app&quot;)/div[@class=&quot;layout-default&quot;]/div[@class=&quot;th-modal-backdrop fullpage visible&quot;]/div[@class=&quot;th-modal-container fullpage fullpage-active&quot;]/div[@class=&quot;modal-flex-centering&quot;]/div[@class=&quot;th-modal contactsNewApollo fullpage apollo&quot;]/div[@class=&quot;modal-content&quot;]/contact-modal[1]/th-modal-body[1]/ng-transclude[1]/form[@class=&quot;max-width-1000 ml-auto mr-auto ng-pristine ng-invalid ng-invalid-required ng-valid-max-file-size ng-valid-invalid-file-format ng-valid-email ng-valid-pattern ng-valid-minlength ng-valid-maxlength&quot;]/th-card[1]/section[@class=&quot;th-card content-padding&quot;]/div[@class=&quot;card-content-container&quot;]/div[1]/th-card-content[1]/cc-web-site-fields[1]/ng-transclude[@class=&quot;th-radio-group ng-not-empty ng-valid&quot;]/div[@class=&quot;ng-pristine ng-valid ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-required&quot;]/span[@class=&quot;th-row&quot;]/th-row[@class=&quot;row justify-content-start&quot;]/th-column[@class=&quot;col col-md-4&quot;]/label[@class=&quot;th-label&quot;]/span[@class=&quot;th-input-wrapper ng-empty ng-valid&quot;]/input[@class=&quot;th-input ng-pristine ng-untouched ng-valid ng-empty ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-required&quot;]</value>
      <webElementGuid>f783c7ea-1434-4424-aeae-31be6388acf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='webSiteAddress']</value>
      <webElementGuid>295f552c-f21f-42d9-ab1a-8f6cb80c0da7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apollo-app']/div/div/div/div/div/div/contact-modal/th-modal-body/ng-transclude/form/th-card/section/div[2]/div/th-card-content/cc-web-site-fields/ng-transclude/div/span/th-row/th-column/label/span[2]/input</value>
      <webElementGuid>985c536c-8b4e-4807-88e2-bbedb67114a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cc-web-site-fields/ng-transclude/div/span/th-row/th-column/label/span[2]/input</value>
      <webElementGuid>81199e8c-9ce4-4722-964a-83c367f72e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'webSiteAddress']</value>
      <webElementGuid>8d68bdb1-eb6d-4309-b15d-d1367fe19e46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
