<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__number</name>
   <tag></tag>
   <elementGuidId>b86d7576-6d32-4530-bf23-956f64ba8986</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;number&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9aab71bd-ecf7-4177-bd8b-6e68aee5af92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>input.ngModel</value>
      <webElementGuid>73da4c94-2a88-4790-9556-8d4c70434442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>th-input ng-pristine ng-untouched ng-valid ng-empty ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-required</value>
      <webElementGuid>7f123b81-25f8-4d2b-8163-184846af2bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>[
      {'with-icon': input.icon},
      {'with-prefix': input.prefix},
      {'with-postfix': input.postfix},
      {'disabled': input.ngDisabled}
    ]</value>
      <webElementGuid>12fad0fc-8152-40a6-a0fc-715d11a9babd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e740156f-3edd-4ee1-a7e5-35922ae47f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>40fa556a-0405-4e17-b53c-911fa937f132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>input.ngRequired</value>
      <webElementGuid>9deaccb1-0010-4ae4-ba0d-14489a4c289f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>input.ngDisabled</value>
      <webElementGuid>b827ce0d-e6cc-4c3d-9ec0-55891f909bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>input.ngBlur()</value>
      <webElementGuid>6779fccf-ef67-4aff-b833-b53013cf8e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keypress</name>
      <type>Main</type>
      <value>input.ngKeypress</value>
      <webElementGuid>d0402405-5812-42dc-9eb9-51926d6075b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-min</name>
      <type>Main</type>
      <value>{{input.min}}</value>
      <webElementGuid>f874de28-44b6-46a5-be06-7f199ff35213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-max</name>
      <type>Main</type>
      <value>{{input.max}}</value>
      <webElementGuid>2b9cc224-c887-43c9-a57b-3007632a9243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-step</name>
      <type>Main</type>
      <value>{{input.step}}</value>
      <webElementGuid>e959d5f6-08d8-4770-b474-d8cb0f33d158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>input.thOnChange()</value>
      <webElementGuid>59a1fd1e-b941-404d-9c4b-2ac841bdb8ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>input.ngReadonly</value>
      <webElementGuid>350477cd-2307-48e0-9482-e5634c878944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model-options</name>
      <type>Main</type>
      <value>{debounce: 500}</value>
      <webElementGuid>e5f22785-2845-40e0-b619-2f1f05819f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Phone number</value>
      <webElementGuid>3700e6e7-3976-4a22-b964-ed4f89074643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8261665c-2005-4c6d-adc0-619a3db50b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apollo-app&quot;)/div[@class=&quot;layout-default&quot;]/div[@class=&quot;th-modal-backdrop fullpage visible&quot;]/div[@class=&quot;th-modal-container fullpage fullpage-active&quot;]/div[@class=&quot;modal-flex-centering&quot;]/div[@class=&quot;th-modal contactsNewApollo fullpage apollo&quot;]/div[@class=&quot;modal-content&quot;]/contact-modal[1]/th-modal-body[1]/ng-transclude[1]/form[@class=&quot;max-width-1000 ml-auto mr-auto ng-pristine ng-invalid ng-invalid-required ng-valid-max-file-size ng-valid-invalid-file-format ng-valid-email ng-valid-pattern ng-valid-minlength ng-valid-maxlength&quot;]/th-card[1]/section[@class=&quot;th-card content-padding&quot;]/div[@class=&quot;card-content-container&quot;]/div[1]/th-card-content[1]/cc-phone-number-fields[1]/ng-transclude[@class=&quot;th-radio-group ng-not-empty ng-valid&quot;]/div[@class=&quot;ng-pristine ng-valid ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-required&quot;]/span[@class=&quot;th-row&quot;]/th-row[@class=&quot;row justify-content-start&quot;]/th-column[@class=&quot;col col-md-4&quot;]/label[@class=&quot;th-label&quot;]/span[@class=&quot;th-input-wrapper ng-empty ng-valid&quot;]/input[@class=&quot;th-input ng-pristine ng-untouched ng-valid ng-empty ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-required&quot;]</value>
      <webElementGuid>e2cc86a4-2abe-4407-8835-5b03ec64ed45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='number']</value>
      <webElementGuid>b0a79815-430b-4a7b-8a6a-21564719c2a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apollo-app']/div/div/div/div/div/div/contact-modal/th-modal-body/ng-transclude/form/th-card/section/div[2]/div/th-card-content/cc-phone-number-fields/ng-transclude/div/span/th-row/th-column/label/span[2]/input</value>
      <webElementGuid>faa7e23b-9297-4c34-8530-066ddda1fa32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cc-phone-number-fields/ng-transclude/div/span/th-row/th-column/label/span[2]/input</value>
      <webElementGuid>45b67a3a-e592-4b99-be59-fb92dc9b0b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'number']</value>
      <webElementGuid>a6f323ba-72a9-4c68-886a-b7cc9294958c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
