<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>cdf58496-cd7d-4ef6-9975-0953e1469978</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.c-header-navigation__primary-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='page-header']/div/nav/div/div/div/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>be6ddefc-d236-4bb0-932d-92e660224641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-header-navigation__primary-link</value>
      <webElementGuid>73a67f8f-0c07-43f5-85b1-5f05f25da178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://account.clio.com?cta=top-nav-na</value>
      <webElementGuid>b7120580-4c3c-43f3-91b3-9fb6fb6d56bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-trigger</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>5e9a9b95-3cfa-4b4d-94f8-4990df698835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-action</name>
      <type>Main</type>
      <value>Login Link</value>
      <webElementGuid>d8cdd195-be5b-420b-aab0-425839ea9fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>3089f494-6ebe-4670-8a6f-c131389e1fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-header&quot;)/div[@class=&quot;c-page-header l-page-header js-header-container&quot;]/nav[@class=&quot;c-header-navigation&quot;]/div[@class=&quot;l-container&quot;]/div[@class=&quot;grid-middle-noGutter&quot;]/div[@class=&quot;col-12&quot;]/ul[@class=&quot;c-header-navigation__items c-header-navigation__items--secondary&quot;]/li[@class=&quot;c-header-navigation__item
		
		is-login
		js-nav-item&quot;]/a[@class=&quot;c-header-navigation__primary-link&quot;]</value>
      <webElementGuid>3c529f53-f284-4249-9162-6a8c6a61e3ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='page-header']/div/nav/div/div/div/ul/li[3]/a</value>
      <webElementGuid>7ecd1f51-7106-4039-8c95-23c7174b8f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>79690a0c-e0f3-4110-8a52-2c63681d15e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Australia'])[1]/following::a[1]</value>
      <webElementGuid>677bf09a-b0ff-4b67-838e-6c85a68258b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ireland'])[1]/following::a[2]</value>
      <webElementGuid>d7c596e8-3c16-4546-b79b-f56068c05993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try For Free'])[1]/preceding::a[2]</value>
      <webElementGuid>14b3afbb-3791-4d61-b5e0-9758fe772511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start a 7 day free trial of Clio.'])[1]/preceding::a[3]</value>
      <webElementGuid>5c3afdde-aed2-4f92-88e8-4f76c2b823ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>fccf428a-f7b0-46c2-ae7c-9f8fd1f2cce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://account.clio.com?cta=top-nav-na')]</value>
      <webElementGuid>40129d75-3e5b-4975-b9f7-66580e668f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>e882b511-ef24-44f6-8ccf-66b413ac4638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://account.clio.com?cta=top-nav-na' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>5334c958-8a2c-4bc0-916c-309fc1869bc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
