<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__date</name>
   <tag></tag>
   <elementGuidId>9f65dabd-e87a-4e86-bd66-97bc121d5503</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;date&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>677acb9d-c13c-4962-9e9f-3354a8547bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>datepicker</value>
      <webElementGuid>f7f81d44-f2d4-4f60-95a4-1a527c11994a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0f689eed-f4a3-405a-bc68-9a4fa00cf021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>666a21e2-e6cf-40ce-af86-f5df629fe7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>d52af2a0-9731-4105-97a9-9bd5216a1755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b1dafded-8522-428f-ad2e-d85b00b237ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>94c7bc5d-ea58-4d83-b7e2-70c8aac7cf8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>726eae9c-ad75-4577-ae95-142d327b69c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>mm/dd/yyyy</value>
      <webElementGuid>70aa591e-2f73-43f8-9638-f75b6b9e28f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>21d8a5af-8f60-4118-9e72-002d560a58e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select date</value>
      <webElementGuid>64e4f361-eba9-4a44-a666-9dd99b649940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>grid</value>
      <webElementGuid>aad0d77c-9e20-41d1-9a41-4c312ccd1343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apollo-app&quot;)/div[@class=&quot;layout-default&quot;]/div[@class=&quot;th-modal-backdrop visible&quot;]/div[@class=&quot;th-modal-container medium&quot;]/div[@class=&quot;modal-flex-centering&quot;]/div[@class=&quot;th-modal apollo-create-task-modal medium&quot;]/div[@class=&quot;modal-content&quot;]/cc-create-task-modal[1]/cc-task-modal[1]/th-modal-body[1]/ng-transclude[1]/form[@class=&quot;task-form ng-pristine ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-pattern ng-valid-minlength&quot;]/cc-task-due-date[1]/div[@class=&quot;task-due-date&quot;]/div[2]/div[@class=&quot;has-margin-bottom&quot;]/span[@class=&quot;th-row&quot;]/th-row[@class=&quot;row justify-content-start&quot;]/th-column[@class=&quot;col col-md-12&quot;]/label[@class=&quot;th-label&quot;]/th-date-picker[@class=&quot;date-picker ng-pristine ng-untouched ng-valid ng-not-empty&quot;]/span[@class=&quot;k-widget k-datepicker k-header&quot;]/span[@class=&quot;k-picker-wrap k-state-default k-state-hover&quot;]/input[@class=&quot;k-input&quot;]</value>
      <webElementGuid>2162a278-1408-4c79-a000-159a3a9fc120</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='date']</value>
      <webElementGuid>3a2666dd-cb02-4fae-84cf-8f0bbb24c0c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apollo-app']/div/div/div/div/div/div/cc-create-task-modal/cc-task-modal/th-modal-body/ng-transclude/form/cc-task-due-date/div/div[2]/div/span/th-row/th-column/label/th-date-picker/span/span/input</value>
      <webElementGuid>da5db630-654e-4fe1-a085-1994e768ffb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th-date-picker/span/span/input</value>
      <webElementGuid>d5e37da1-abe3-45a7-b5b3-6c6c3ec1ce30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'date' and @placeholder = 'mm/dd/yyyy']</value>
      <webElementGuid>b2d62c01-7ed2-4559-b20b-990f906b5f6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
