<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__matter_input</name>
   <tag></tag>
   <elementGuidId>9b22759d-ce85-4746-96fa-a6296e15486b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;matter_input&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='matter_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73666957-a968-46bc-bdb7-3e9778fdee7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>matter_input</value>
      <webElementGuid>daa9c59e-a057-441f-a95e-8b01d176a356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>1b4d4090-6fe9-4585-973d-24fff735f566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4e8e034d-d08d-471d-bdfa-d19620bd9359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>73021259-6819-4022-9abb-62bbd58d104c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>a703c656-5c4e-4eba-909a-454d4b3b54a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bd11f399-de9b-4cc8-bd8e-0ec115d53fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Find a matter...</value>
      <webElementGuid>ae3ee250-29f5-46d3-800e-7ecf8304b445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8bb5efaf-1b57-4f67-b9ef-1af9d7ac1432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d3620d5a-d47c-46eb-a42d-6b7762c50a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>d8bfc82c-507a-4053-9730-d6c820a95ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-busy</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>478df670-4567-4105-a2dc-538674d9f366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>a7c58da6-8379-406a-9314-d655614e140e</value>
      <webElementGuid>db896eaf-7bc3-4f26-af2b-58806996390d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apollo-app&quot;)/div[@class=&quot;layout-default&quot;]/div[@class=&quot;th-modal-backdrop visible&quot;]/div[@class=&quot;th-modal-container medium&quot;]/div[@class=&quot;modal-flex-centering&quot;]/div[@class=&quot;th-modal apollo-create-task-modal medium&quot;]/div[@class=&quot;modal-content&quot;]/cc-create-task-modal[1]/cc-task-modal[1]/th-modal-body[1]/ng-transclude[1]/form[@class=&quot;task-form ng-pristine ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-pattern ng-valid-minlength&quot;]/cc-task-related-matter[1]/div[@class=&quot;task-related-matter&quot;]/cc-matter-field[@class=&quot;ng-pristine ng-untouched ng-valid ng-empty&quot;]/div[@class=&quot;ng-pristine ng-valid ng-valid-required&quot;]/div[1]/label[@class=&quot;th-label&quot;]/th-combobox[@class=&quot;ng-pristine ng-untouched ng-valid ng-empty ng-valid-required&quot;]/span[@class=&quot;th-combobox-container no-value&quot;]/span[@class=&quot;k-widget k-combobox k-header k-combobox-clearable&quot;]/span[@class=&quot;k-dropdown-wrap k-state-default k-state-hover&quot;]/input[@class=&quot;k-input&quot;]</value>
      <webElementGuid>0f76e117-b7ee-4c30-b353-9d85b7ff7b23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='matter_input']</value>
      <webElementGuid>c41452d0-2fb4-4536-8810-970ee47aa7a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apollo-app']/div/div/div/div/div/div/cc-create-task-modal/cc-task-modal/th-modal-body/ng-transclude/form/cc-task-related-matter/div/cc-matter-field/div/div/label/th-combobox/span/span/span/input</value>
      <webElementGuid>5602ad1b-95cc-4dcb-b9b9-4ec449452ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cc-matter-field/div/div/label/th-combobox/span/span/span/input</value>
      <webElementGuid>ba4a4424-c817-4517-862a-d7a51d5c487e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'matter_input' and @type = 'text' and @placeholder = 'Find a matter...']</value>
      <webElementGuid>2d9463d0-a208-4cac-b37b-57e3772d3c26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
