<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__assignTo_input</name>
   <tag></tag>
   <elementGuidId>e940c982-fbab-4b93-8e64-34c7406de6bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;assignTo_input&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='assignTo_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1d202b8-4ab2-47a3-95cb-351cb0d6e017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>assignTo_input</value>
      <webElementGuid>4b868e9f-ae2a-4fb2-81e1-dee4dd87ef50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>7eb63e52-6aa7-4951-958d-b4ff4173e6bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>86749147-60fb-4260-8092-c7b84d4a1466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>261ece8a-1cda-4d9b-8b32-3517d002df99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>9bb8a1d1-22e6-4a98-a3b0-ba8412be33a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4684a022-6100-42ea-9af6-cfbdc876df61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select an assignee</value>
      <webElementGuid>31aa8638-5454-44fe-a9b7-5ed021ce7858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>919eacd6-bf75-41b2-88a0-5293c5498cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>26993598-83a1-4500-b5a6-5e7a4c54d99f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>fa00bd3a-9ae2-4d68-a458-cfe2cc49afba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-busy</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>527ca5d6-4ebc-4e97-a106-a80d87190ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>0e5eef32-cd5a-4b01-9645-ac0441fdd575</value>
      <webElementGuid>89a4247e-0647-4caf-8b21-f2f693f58255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apollo-app&quot;)/div[@class=&quot;layout-default&quot;]/div[@class=&quot;th-modal-backdrop visible&quot;]/div[@class=&quot;th-modal-container medium&quot;]/div[@class=&quot;modal-flex-centering&quot;]/div[@class=&quot;th-modal apollo-create-task-modal medium&quot;]/div[@class=&quot;modal-content&quot;]/cc-create-task-modal[1]/cc-task-modal[1]/th-modal-body[1]/ng-transclude[1]/form[@class=&quot;task-form ng-pristine ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-pattern ng-valid-minlength&quot;]/span[@class=&quot;th-row&quot;]/th-row[@class=&quot;row justify-content-center&quot;]/th-column[@class=&quot;col col-md-8&quot;]/cc-task-assign-to[1]/div[@class=&quot;task-assign-to&quot;]/div[@class=&quot;has-margin-bottom&quot;]/label[@class=&quot;th-label&quot;]/th-combobox[@class=&quot;ng-pristine ng-untouched ng-valid ng-not-empty ng-valid-required&quot;]/span[@class=&quot;th-combobox-container&quot;]/span[@class=&quot;k-widget k-combobox k-header k-combobox-clearable&quot;]/span[@class=&quot;k-dropdown-wrap k-state-default k-state-hover&quot;]/input[@class=&quot;k-input&quot;]</value>
      <webElementGuid>68eb20d4-c864-43bd-8d11-f0ac0ada6818</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='assignTo_input']</value>
      <webElementGuid>648cb5c8-6e5f-4112-a288-8afd2407787b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apollo-app']/div/div/div/div/div/div/cc-create-task-modal/cc-task-modal/th-modal-body/ng-transclude/form/span[2]/th-row/th-column/cc-task-assign-to/div/div/label/th-combobox/span/span/span/input</value>
      <webElementGuid>c4a41fa2-ef6d-481e-a765-fa9312a66f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/input</value>
      <webElementGuid>4a4b0507-71b4-4899-a361-032cde399d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'assignTo_input' and @type = 'text' and @placeholder = 'Select an assignee']</value>
      <webElementGuid>710b79d7-2cbc-4276-beb8-2d47aaf05894</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
