<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__description</name>
   <tag></tag>
   <elementGuidId>4046d9ca-d20a-4441-aab6-592270737013</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;description&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d4247a69-5d95-40fa-8aa7-8703b6ee330c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>69dd321a-dca3-40b3-bc8d-d790f3708ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-name</name>
      <type>Main</type>
      <value>{{ctrl.name}}</value>
      <webElementGuid>b787f834-5a17-49e5-8118-89cb567483f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-placeholder</name>
      <type>Main</type>
      <value>{{ctrl.placeholder}}</value>
      <webElementGuid>2948ba4e-9f0d-4530-a5dd-e70835d3bbdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-rows</name>
      <type>Main</type>
      <value>{{ctrl.rows}}</value>
      <webElementGuid>fcf81d26-229e-4f89-85da-59ddef91367b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>ctrl.ngBlur()</value>
      <webElementGuid>295b9a07-2b19-455b-b503-7e984ec4dc56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>ctrl.thOnChange()</value>
      <webElementGuid>857acbf4-bed3-4ffa-9c03-47e4cb70819e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>[
    {'with-icon': ctrl.icon},
    {'disabled': ctrl.ngDisabled},
    {'is-invalid': ctrl.isInvalid()}
  ]</value>
      <webElementGuid>1032743f-e932-470a-8308-b0a0d18c8517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>ctrl.ngDisabled</value>
      <webElementGuid>0762fb71-773e-4438-b34c-62180766a6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-maxlength</name>
      <type>Main</type>
      <value>65535</value>
      <webElementGuid>9edaadd1-3409-448e-89d9-f10b5130efd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>ctrl.model</value>
      <webElementGuid>66d05fda-7342-40f7-a041-f209f2c5c63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>ctrl.ngRequired</value>
      <webElementGuid>e5383959-95ed-44bb-82fa-5a74578419ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>71377db1-50d3-453b-8abe-08459ff5294e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid task-form__description ng-empty ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-required</value>
      <webElementGuid>6b4af599-2972-466e-8b26-17eac11d5031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>09e821ed-fa16-4d0c-b095-30671250cf81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>28503ec9-b1ed-4cee-b267-6dfb02435677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter task description...</value>
      <webElementGuid>7dd1f6b9-9484-4836-a7f4-286196b2d025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>df34a191-302e-4f3f-8707-722abf15ddc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apollo-app&quot;)/div[@class=&quot;layout-default&quot;]/div[@class=&quot;th-modal-backdrop visible&quot;]/div[@class=&quot;th-modal-container medium&quot;]/div[@class=&quot;modal-flex-centering&quot;]/div[@class=&quot;th-modal apollo-create-task-modal medium&quot;]/div[@class=&quot;modal-content&quot;]/cc-create-task-modal[1]/cc-task-modal[1]/th-modal-body[1]/ng-transclude[1]/form[@class=&quot;task-form ng-pristine ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-pattern ng-valid-minlength&quot;]/label[@class=&quot;th-label&quot;]/th-textarea[@class=&quot;ng-pristine ng-untouched ng-valid ng-empty ng-valid-maxlength&quot;]/textarea[@class=&quot;ng-pristine ng-untouched ng-valid task-form__description ng-empty ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-required&quot;]</value>
      <webElementGuid>1d4ef47d-5847-41ab-adca-d9e2e2a1b594</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='description']</value>
      <webElementGuid>aa1f8669-0b7d-493b-a46f-d716254f7319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apollo-app']/div/div/div/div/div/div/cc-create-task-modal/cc-task-modal/th-modal-body/ng-transclude/form/label/th-textarea/textarea</value>
      <webElementGuid>b5cc433d-60f0-4d69-bf43-f4baa2e974f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>b7569391-7153-4066-956a-3fcb13e5fa03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'description' and @placeholder = 'Enter task description...']</value>
      <webElementGuid>8995aaf3-fcd5-4047-8038-3e21f52025a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
