<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__relationship</name>
   <tag></tag>
   <elementGuidId>e1dba159-f355-4484-a5a0-8325c72b082b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;relationship&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='relationship']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65a16db9-bd22-418f-a012-d127d2fa96ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>input.ngModel</value>
      <webElementGuid>38784844-9a9f-4ae2-aa39-556d6189ac89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>th-input ng-pristine ng-untouched ng-valid ng-empty ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-required</value>
      <webElementGuid>a60fbad9-bfb8-42a3-a5c2-d5275a085859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>[
      {'with-icon': input.icon},
      {'with-prefix': input.prefix},
      {'with-postfix': input.postfix},
      {'disabled': input.ngDisabled}
    ]</value>
      <webElementGuid>14f80f80-e667-4bf0-9f16-2e2dd15b57ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5e3c00e3-3ff6-4f03-9cd1-a0571bc9c6a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>relationship</value>
      <webElementGuid>86f845ae-ab0e-444c-9b6a-47d880bde8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>input.ngRequired</value>
      <webElementGuid>9faeffc7-604d-4603-b364-39a67319b6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>input.ngDisabled</value>
      <webElementGuid>c167c21d-4902-4a35-938c-81b195016dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>input.ngBlur()</value>
      <webElementGuid>145ddbe6-56f8-436e-91d9-4c05affbb2e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keypress</name>
      <type>Main</type>
      <value>input.ngKeypress</value>
      <webElementGuid>e2f534d0-fb2c-437a-a7df-72cf1c36c1de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>898dfc0d-75bc-44c7-a5dd-8eb61afacce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-min</name>
      <type>Main</type>
      <value>{{input.min}}</value>
      <webElementGuid>2c07fb6a-5b58-4d36-978d-ec63cc7b3e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-max</name>
      <type>Main</type>
      <value>{{input.max}}</value>
      <webElementGuid>43fe4670-caf3-43b7-8eef-5114d6c15ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-step</name>
      <type>Main</type>
      <value>{{input.step}}</value>
      <webElementGuid>2131f8e2-55fb-4dcf-8f8a-430d9ddb373a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>input.thOnChange()</value>
      <webElementGuid>68a4a180-94c6-4264-9046-8a76fa91f3ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>input.ngReadonly</value>
      <webElementGuid>9fdb118f-4e27-4ef0-8c58-f199fc7f7183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>undefined</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>04f4daec-7c33-49f6-b3c6-3d01bd209003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Relationship</value>
      <webElementGuid>685839f5-d26f-4c47-b090-5366c58ec739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6e9b6dea-487b-4ec3-8d53-cf823353098e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;related-contact-0&quot;)/ng-form[@class=&quot;related-contact ng-pristine ng-valid ng-valid-maxlength ng-valid-required ng-valid-pattern ng-valid-minlength&quot;]/span[@class=&quot;th-row&quot;]/th-row[@class=&quot;row justify-content-center&quot;]/th-column[@class=&quot;col&quot;]/div[@class=&quot;related-contact__contact-relationship&quot;]/label[@class=&quot;th-label&quot;]/span[@class=&quot;th-input-wrapper ng-empty ng-valid ng-valid-maxlength has-focus&quot;]/input[@class=&quot;th-input ng-pristine ng-untouched ng-valid ng-empty ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-required&quot;]</value>
      <webElementGuid>986a249d-10e0-41c8-b4b6-d2290e750648</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='relationship']</value>
      <webElementGuid>e3f03657-4beb-4799-bef1-f1e381731a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//cc-related-contact[@id='related-contact-0']/ng-form/span/th-row/th-column[2]/div/label/span[2]/input</value>
      <webElementGuid>bd5f8ccc-d4ce-4ab9-960f-86286cabd08b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/label/span[2]/input</value>
      <webElementGuid>c723bdb7-8535-48fc-8e32-e51ba809d32e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'relationship']</value>
      <webElementGuid>c287a01f-5438-46dc-afb9-c4b6d8988b57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
