<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__client_input</name>
   <tag></tag>
   <elementGuidId>76ae3a0c-76ef-4002-a2d9-ff5086c5692f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;client_input&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='client_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eda58ecb-b895-4f33-a647-3db8f73b03bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>client_input</value>
      <webElementGuid>e5f71968-c7e7-44a8-8694-e26dc8b8868e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>c0f0d3fc-dee3-4fbc-9010-00c778242ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef740532-df76-46a8-b473-67a579c320b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9e10e75d-151c-4594-89ef-7c2a3cafd2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>459190ce-1604-4689-bb50-a95ecffbb8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9a464a34-8c00-4f21-ae33-8561eda89100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>What’s the contact’s name?</value>
      <webElementGuid>c926386c-8652-4498-800f-3a24d8be42b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5344da0e-af90-48e7-b831-c8acdc0e592e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8d5b341f-e426-42e3-af65-1c490c8cc07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>7ba2b096-6308-406f-a0ff-23c20a8e1508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-busy</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5113518b-218d-40de-aca4-ae3b23956146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>43d8d9f9-52dd-4d8e-b17e-6469a1e8256b</value>
      <webElementGuid>eed48f65-5283-45ba-806e-c308cfff7dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;matter_details&quot;)/ng-form[@class=&quot;matter-form-details ng-pristine ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-pattern ng-valid-minlength&quot;]/section[@class=&quot;matter-form__section-content&quot;]/cc-contact-field[@class=&quot;ng-pristine ng-untouched ng-valid ng-not-empty&quot;]/div[@class=&quot;ng-pristine ng-valid ng-valid-required&quot;]/label[@class=&quot;th-label&quot;]/th-combobox[@class=&quot;ng-pristine ng-untouched ng-not-empty ng-valid ng-valid-required&quot;]/span[@class=&quot;th-combobox-container&quot;]/span[@class=&quot;k-widget k-combobox k-header k-combobox-clearable&quot;]/span[@class=&quot;k-dropdown-wrap k-state-default k-state-focused k-state-hover&quot;]/input[@class=&quot;k-input&quot;]</value>
      <webElementGuid>a5236b57-bad5-45c3-8e2e-cbc94eb61aed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='client_input']</value>
      <webElementGuid>08c4c240-5c26-4963-a738-dae7c28ab8b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//cc-matter-form-details[@id='matter_details']/ng-form/section/cc-contact-field/div/label/th-combobox/span/span/span/input</value>
      <webElementGuid>8d7b0191-d825-40e7-a19e-d23c7475860a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/label/th-combobox/span/span/span/input</value>
      <webElementGuid>3cadea15-5f98-434b-906e-8554c864a216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'client_input' and @type = 'text' and @placeholder = 'What’s the contact’s name?']</value>
      <webElementGuid>c73c44cd-b1e8-44b1-a443-1f8ea8e077be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
