<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Alwa Corp (noemailalwa.corp)</name>
   <tag></tag>
   <elementGuidId>e249bcea-d070-4ce3-b943-71325d8cd693</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fe6b6c73-dc7e-4b78-9b98-59c3d4100ac9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='fe6b6c73-dc7e-4b78-9b98-59c3d4100ac9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e57725c7-67b7-461f-9602-0e5a26a1f86e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>daf8ab7a-c740-4d18-b94d-415a85c1c3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>c807ef40-cc1e-4c37-b0c3-b4da5410410a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>ebcbe739-934c-439e-bcf5-a960d5b8e347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-focused k-state-hover</value>
      <webElementGuid>d0f7a583-0a9a-4652-beae-64b1f1e5c8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4f0638a4-6597-4686-8860-183c97d7b188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>de6a5772-3dd3-4f77-bf0b-74c6fba50571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fe6b6c73-dc7e-4b78-9b98-59c3d4100ac9</value>
      <webElementGuid>63118d10-af33-41ad-a8db-f0b2a5dd85ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alwa Corp (noemail@alwa.corp)</value>
      <webElementGuid>404ba88e-8c3e-4a09-a122-bffb9ee5e055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fe6b6c73-dc7e-4b78-9b98-59c3d4100ac9&quot;)</value>
      <webElementGuid>ac884677-3f38-4454-a72b-2611febc0086</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='fe6b6c73-dc7e-4b78-9b98-59c3d4100ac9']</value>
      <webElementGuid>f12f3dce-0b67-4de8-aa94-398c3a5f9047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Companies'])[1]/following::li[1]</value>
      <webElementGuid>0d19180b-46b3-4a0c-9743-adfb052cf1e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No results found.'])[3]/following::li[1]</value>
      <webElementGuid>71251602-dbb6-411e-91ae-007eba43b5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div[2]/ul/li</value>
      <webElementGuid>99f66c63-1a07-447d-88a5-78fdc4209439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'fe6b6c73-dc7e-4b78-9b98-59c3d4100ac9' and (text() = 'Alwa Corp (noemail@alwa.corp)' or . = 'Alwa Corp (noemail@alwa.corp)')]</value>
      <webElementGuid>5044716e-b25f-458f-8419-ce912e809ddb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
