<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Company_Name</name>
   <tag></tag>
   <elementGuidId>32a38d16-f8c8-4df5-b3f8-b8b531538f97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fe6b6c73-dc7e-4b78-9b98-59c3d4100ac9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='fe6b6c73-dc7e-4b78-9b98-59c3d4100ac9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2cd09bc0-e69a-497e-84c4-f7054454ebfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d96eb49f-71e6-465c-a3df-231f2279837b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>a78bbebb-357f-4e76-aec2-2fabff66decd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>6016e238-f1ae-4388-a4d2-f393662e1293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-focused k-state-hover</value>
      <webElementGuid>7d0c827c-7ff1-4a0d-b72e-8e779363bebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b3db43c4-0570-42ff-839f-43c0bee06fc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>af0b022b-09b6-4451-a61c-1c0dc941cde5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fe6b6c73-dc7e-4b78-9b98-59c3d4100ac9</value>
      <webElementGuid>43f9ebcd-e282-4023-9d9e-20e7657ad556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Company_Name (company@gmail.com)</value>
      <webElementGuid>5466820a-6fd1-4192-a598-959ab98b3197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fe6b6c73-dc7e-4b78-9b98-59c3d4100ac9&quot;)</value>
      <webElementGuid>c79fdf32-d62c-4abc-be80-50dc2b9f41be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='fe6b6c73-dc7e-4b78-9b98-59c3d4100ac9']</value>
      <webElementGuid>afd0b2ea-222b-4ab8-aba0-10eeec291f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Companies'])[1]/following::li[1]</value>
      <webElementGuid>61a57ee6-4d3d-48c7-b8dc-1bd820857980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No results found.'])[3]/following::li[1]</value>
      <webElementGuid>da2bf859-61d4-4f53-911a-0e3059b06e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div[2]/ul/li</value>
      <webElementGuid>70d7078a-a36c-4874-a04b-3581bd2267ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'fe6b6c73-dc7e-4b78-9b98-59c3d4100ac9' and (text() = 'Company_Name (company@gmail.com)' or . = 'Company_Name (company@gmail.com)')]</value>
      <webElementGuid>ba760a0f-8266-4326-b55f-6d5bf5fc2b52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
