<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__k-select</name>
   <tag></tag>
   <elementGuidId>4921f657-3dd2-48c4-9296-76034938f368</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.k-dropdown-wrap.k-state-default.k-state-hover > span.k-select</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//cc-matter-form-details[@id='matter_details']/ng-form/section/cc-contact-field/div/label/th-combobox/span/span/span/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ef91afbe-0955-4b06-802b-7b22a58acbd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>a35f4c34-6694-45d3-8630-778c8c02d53f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-select</value>
      <webElementGuid>ee1e219d-fb98-42d1-a089-8e7ca7d08640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b8f1a1f4-3fee-442d-8790-7eb44d9cf509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0e2a726b-b762-4adb-b12e-d7c04db229c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>abdd2fea-f891-451c-beae-1f00245c6f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;matter_details&quot;)/ng-form[@class=&quot;matter-form-details ng-pristine ng-invalid ng-invalid-required ng-valid-maxlength ng-valid-pattern ng-valid-minlength&quot;]/section[@class=&quot;matter-form__section-content&quot;]/cc-contact-field[@class=&quot;ng-pristine ng-untouched ng-valid ng-empty&quot;]/div[@class=&quot;ng-pristine ng-invalid ng-invalid-required&quot;]/label[@class=&quot;th-label&quot;]/th-combobox[@class=&quot;ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required&quot;]/span[@class=&quot;th-combobox-container no-value&quot;]/span[@class=&quot;k-widget k-combobox k-header k-combobox-clearable&quot;]/span[@class=&quot;k-dropdown-wrap k-state-default k-state-hover&quot;]/span[@class=&quot;k-select&quot;]</value>
      <webElementGuid>e819ee1a-e19b-446f-a875-5a4394183650</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//cc-matter-form-details[@id='matter_details']/ng-form/section/cc-contact-field/div/label/th-combobox/span/span/span/span[2]</value>
      <webElementGuid>4e1fd17f-efb6-4ad9-a036-5c014b8d9741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::span[5]</value>
      <webElementGuid>5a19fde6-0e71-4cb9-8f2f-fb8db1631d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client'])[1]/following::span[6]</value>
      <webElementGuid>ba247273-8ceb-4142-ac50-4f88efcee6d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Matter description'])[1]/preceding::span[2]</value>
      <webElementGuid>3ca44606-64e3-47de-a46e-6632e1b6f08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/preceding::span[2]</value>
      <webElementGuid>f182ecb8-d831-423d-a670-3b3023a2689c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span[2]</value>
      <webElementGuid>8131ea6a-4405-45fd-bc69-6e5e77752d70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
