<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__userFieldAutocomplete_input</name>
   <tag></tag>
   <elementGuidId>c633bad8-34a6-4fd9-b213-d4f63433d4d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;userFieldAutocomplete_input&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='userFieldAutocomplete_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1263335-a982-46cf-9a4f-236716f62c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userFieldAutocomplete_input</value>
      <webElementGuid>a7bbd266-97dd-4ab9-be77-63b27cc6ae4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-input</value>
      <webElementGuid>63deed00-f278-4279-9d95-c07536e6fc51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb6249c7-6b55-4d34-a68e-2d9d571e77fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>766a39dc-b05c-4928-b621-e3a1f35f828e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>f97fd225-ae5e-457d-89dd-fc79b7b7071d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0b98d429-c938-4aa0-a63e-acf019f852ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Find a firm user</value>
      <webElementGuid>86e3fa2a-bcb9-4927-aad4-9b29ed744b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>059d9f9e-c198-448c-a076-9bcf895cc8bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>edd0359d-433d-410f-8d05-7fd40b54f49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>929ae55e-32da-4b6a-a1b4-c836931954dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-busy</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3264d389-23f3-40fb-82a9-f21c6ad84272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>04d14746-0a2d-4a39-8e2c-90f7106a0b79</value>
      <webElementGuid>c4465592-53d6-4cb0-81ac-673137f0680a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apollo-app&quot;)/div[@class=&quot;layout-default&quot;]/div[@class=&quot;th-modal-backdrop visible&quot;]/div[@class=&quot;th-modal-container medium&quot;]/div[@class=&quot;modal-flex-centering&quot;]/div[@class=&quot;th-modal apollo-time-entry-modal medium apollo&quot;]/div[@class=&quot;modal-content&quot;]/cc-activities-time-entry-form[1]/th-modal-body[1]/ng-transclude[1]/form[@class=&quot;modal-form time-entry-form ng-pristine ng-valid ng-valid-required ng-valid-pattern ng-valid-minlength ng-valid-maxlength&quot;]/div[@class=&quot;form-content&quot;]/span[@class=&quot;th-row&quot;]/th-row[@class=&quot;row justify-content-center&quot;]/th-column[@class=&quot;col col-md-6&quot;]/cc-user-field[@class=&quot;ng-pristine ng-untouched ng-valid ng-not-empty ng-valid-required&quot;]/div[@class=&quot;ng-pristine ng-valid ng-valid-required&quot;]/label[@class=&quot;th-label&quot;]/th-combobox[@class=&quot;ng-pristine ng-untouched ng-valid ng-not-empty ng-valid-required&quot;]/span[@class=&quot;th-combobox-container&quot;]/span[@class=&quot;k-widget k-combobox k-header k-combobox-clearable&quot;]/span[@class=&quot;k-dropdown-wrap k-state-default k-state-hover&quot;]/input[@class=&quot;k-input&quot;]</value>
      <webElementGuid>80dedd97-3c95-4670-92d6-d20c23776394</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='userFieldAutocomplete_input']</value>
      <webElementGuid>76e48ef3-a4f6-41e3-ad84-82afca4206fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apollo-app']/div/div/div/div/div/div/cc-activities-time-entry-form/th-modal-body/ng-transclude/form/div/span[3]/th-row/th-column[2]/cc-user-field/div/label/th-combobox/span/span/span/input</value>
      <webElementGuid>c97ace53-93c3-4f76-817b-6416bab3d51b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cc-user-field/div/label/th-combobox/span/span/span/input</value>
      <webElementGuid>0ed1f90d-f655-4ed2-a0e6-41c7052736d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'userFieldAutocomplete_input' and @type = 'text' and @placeholder = 'Find a firm user']</value>
      <webElementGuid>ee43e964-b930-40d8-b0c2-eacf12ce6634</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
