<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__rateField</name>
   <tag></tag>
   <elementGuidId>82c29d07-bbfc-4070-af21-211aea617dc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;rateField&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='rateField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca99d3cd-67d9-482f-873e-d11f4f0b0f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>input.ngModel</value>
      <webElementGuid>a99f7824-ea08-4783-81cd-4ac48b17587c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>th-input ng-pristine ng-untouched ng-valid ng-not-empty ng-valid-required ng-valid-pattern ng-valid-minlength ng-valid-maxlength with-postfix</value>
      <webElementGuid>7fea5e23-67f9-4d1d-9ce6-4a9b37711ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>[
      {'with-icon': input.icon},
      {'with-prefix': input.prefix},
      {'with-postfix': input.postfix},
      {'disabled': input.ngDisabled}
    ]</value>
      <webElementGuid>36221916-382d-40dc-a4d5-2dbfd5b2268c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f55f9138-c1cd-4864-a573-389a65637f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rateField</value>
      <webElementGuid>138852d3-6cef-4136-ae3d-8d88fe5d991e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0.00</value>
      <webElementGuid>d6a4686c-9715-4a6c-9578-9f92b3d39dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>input.ngRequired</value>
      <webElementGuid>6c935bd7-21f0-4754-8667-d0316adc1536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>input.ngDisabled</value>
      <webElementGuid>527c0de9-42f1-4b36-ac0c-1161ab3ad6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>input.ngBlur()</value>
      <webElementGuid>67b3a66a-1217-4547-8fd4-0e1d092c09cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-keypress</name>
      <type>Main</type>
      <value>input.ngKeypress</value>
      <webElementGuid>8a861f72-c193-4d7b-b9b0-efdfe4a63962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-pattern</name>
      <type>Main</type>
      <value>/^-?\d*\.?\d{0,2}$/</value>
      <webElementGuid>7629bf19-57e7-4ff5-a310-a4dfff0f37d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-min</name>
      <type>Main</type>
      <value>{{input.min}}</value>
      <webElementGuid>7515b3f6-3ce6-43fb-90f0-ddc72916a7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-max</name>
      <type>Main</type>
      <value>{{input.max}}</value>
      <webElementGuid>41bce5da-19fe-440e-8cf1-ff383b5cb6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-step</name>
      <type>Main</type>
      <value>{{input.step}}</value>
      <webElementGuid>adabd6f8-112e-4199-b475-ddc4dc3577bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>input.thOnChange()</value>
      <webElementGuid>007d4325-ca46-41b8-9bfa-36e2b6c694d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-readonly</name>
      <type>Main</type>
      <value>input.ngReadonly</value>
      <webElementGuid>49b61e5d-705f-40d6-8e01-8b8699d93642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>highlight</name>
      <type>Main</type>
      <value>highlight-rate-field</value>
      <webElementGuid>1808d59e-f6a4-4d43-9941-7fa981c3f381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-e2e</name>
      <type>Main</type>
      <value>rate</value>
      <webElementGuid>867f44f5-74a0-4407-a4f5-03933830f97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>undefined</name>
      <type>Main</type>
      <value>$ctrl.rateFieldRegex</value>
      <webElementGuid>12850086-ef34-4cb8-9702-8a1af3435d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Rate</value>
      <webElementGuid>03e29f6e-9859-40e9-b4da-c3b6f1b96da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>b4fa7396-56a8-40b4-827d-d1edab4a46a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1a0c3854-dc5f-467c-a997-e27930261968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apollo-app&quot;)/div[@class=&quot;layout-default&quot;]/div[@class=&quot;th-modal-backdrop visible&quot;]/div[@class=&quot;th-modal-container medium&quot;]/div[@class=&quot;modal-flex-centering&quot;]/div[@class=&quot;th-modal apollo-time-entry-modal medium apollo&quot;]/div[@class=&quot;modal-content&quot;]/cc-activities-time-entry-form[1]/th-modal-body[1]/ng-transclude[1]/form[@class=&quot;modal-form time-entry-form ng-pristine ng-valid ng-valid-required ng-valid-pattern ng-valid-minlength ng-valid-maxlength&quot;]/div[@class=&quot;form-content&quot;]/span[@class=&quot;th-row&quot;]/th-row[@class=&quot;row justify-content-center&quot;]/th-column[@class=&quot;col col-md-6&quot;]/cc-activities-rate-field[@class=&quot;ng-pristine ng-untouched ng-valid ng-not-empty ng-valid-required&quot;]/div[@class=&quot;split ng-pristine ng-valid ng-valid-required ng-valid-pattern ng-valid-minlength ng-valid-maxlength&quot;]/label[@class=&quot;th-label&quot;]/span[@class=&quot;th-input-wrapper ng-not-empty ng-valid ng-valid-required ng-valid-pattern condensed&quot;]/input[@class=&quot;th-input ng-pristine ng-untouched ng-valid ng-not-empty ng-valid-required ng-valid-pattern ng-valid-minlength ng-valid-maxlength with-postfix&quot;]</value>
      <webElementGuid>39e783c7-e286-46a0-a748-f247063d0898</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='rateField']</value>
      <webElementGuid>15d9c321-8b5f-4abe-86ff-514941ac7230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apollo-app']/div/div/div/div/div/div/cc-activities-time-entry-form/th-modal-body/ng-transclude/form/div/span[3]/th-row/th-column[2]/cc-activities-rate-field/div/label/span[2]/input</value>
      <webElementGuid>7c0cb815-4a7b-4927-b4e7-f1d4418427f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>53983734-a286-43d8-82c7-eb4115027ea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'rateField' and @placeholder = '0.00']</value>
      <webElementGuid>04e206df-a1fe-4905-9956-c73c21b3e289</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
