<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__ng-pristine ng-untouched ng-valid time-entry-form__description ng-empty ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-required</name>
   <tag></tag>
   <elementGuidId>2d804f00-11ee-41b9-b439-3c98cb20a902</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.ng-pristine.ng-untouched.ng-valid.time-entry-form__description.ng-empty.ng-valid-pattern.ng-valid-minlength.ng-valid-maxlength.ng-valid-required</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apollo-app']/div/div/div/div/div/div/cc-activities-time-entry-form/th-modal-body/ng-transclude/form/div/span[3]/th-row/th-column/div/label/th-textarea/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>41f73a57-2bc7-4471-acde-9d8b1d85cf50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiline</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f172b717-8803-42ea-87ec-819df457b054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-name</name>
      <type>Main</type>
      <value>{{ctrl.name}}</value>
      <webElementGuid>6dc26447-b435-475f-a06f-ad5aa96e460c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-placeholder</name>
      <type>Main</type>
      <value>{{ctrl.placeholder}}</value>
      <webElementGuid>378060d8-7730-4340-8b20-3e68d6b6a327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-attr-rows</name>
      <type>Main</type>
      <value>{{ctrl.rows}}</value>
      <webElementGuid>c12e35ff-13ed-4cab-9bbd-e5245a406428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>ctrl.ngBlur()</value>
      <webElementGuid>9534550c-ba65-490b-a3c2-77cfe4e62e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>ctrl.thOnChange()</value>
      <webElementGuid>90ff2736-db62-4d77-b502-e05cbd7cfcb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-class</name>
      <type>Main</type>
      <value>[
    {'with-icon': ctrl.icon},
    {'disabled': ctrl.ngDisabled},
    {'is-invalid': ctrl.isInvalid()}
  ]</value>
      <webElementGuid>564f5d6a-ecad-45ef-8625-1f4f84b9f806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>ctrl.ngDisabled</value>
      <webElementGuid>073da47b-c708-409a-9d75-4f65018f08f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>ctrl.model</value>
      <webElementGuid>dd90944b-75ba-4344-8b27-abb5e1dc38d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-required</name>
      <type>Main</type>
      <value>ctrl.ngRequired</value>
      <webElementGuid>9b780db6-989e-4160-bb56-a7bd58d229ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>a7a71254-a2ae-42c6-8d59-10acb8c8f7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid time-entry-form__description ng-empty ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-required</value>
      <webElementGuid>c18a7b35-d616-407a-8e75-6580d1e688de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>55c896bc-fa29-4f78-872b-a08b6f06ef57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>331dacd4-20b0-4152-a5e5-0b85254a8f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>47626f5c-f88e-4c3c-be86-44a1816c5463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apollo-app&quot;)/div[@class=&quot;layout-default&quot;]/div[@class=&quot;th-modal-backdrop visible&quot;]/div[@class=&quot;th-modal-container medium&quot;]/div[@class=&quot;modal-flex-centering&quot;]/div[@class=&quot;th-modal apollo-time-entry-modal medium apollo&quot;]/div[@class=&quot;modal-content&quot;]/cc-activities-time-entry-form[1]/th-modal-body[1]/ng-transclude[1]/form[@class=&quot;modal-form time-entry-form ng-pristine ng-valid ng-valid-required ng-valid-pattern ng-valid-minlength ng-valid-maxlength&quot;]/div[@class=&quot;form-content&quot;]/span[@class=&quot;th-row&quot;]/th-row[@class=&quot;row justify-content-center&quot;]/th-column[@class=&quot;col col-md-6&quot;]/div[@class=&quot;description-textarea&quot;]/label[@class=&quot;th-label&quot;]/th-textarea[@class=&quot;ng-pristine ng-untouched ng-valid ng-empty&quot;]/textarea[@class=&quot;ng-pristine ng-untouched ng-valid time-entry-form__description ng-empty ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-required&quot;]</value>
      <webElementGuid>958d7921-6505-45a1-bf36-91ca4128d7a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apollo-app']/div/div/div/div/div/div/cc-activities-time-entry-form/th-modal-body/ng-transclude/form/div/span[3]/th-row/th-column/div/label/th-textarea/textarea</value>
      <webElementGuid>56d7159e-2fa0-4d14-8e09-52e5c781b65d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>7fedeab8-69ff-4e5c-9aba-355728df6645</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
